# 2.4. Perform nested regression with bootstrapping of metric value against magnitude of ablation and biological covariate confluence

Assesses how each metrics is able to capture the variation in ablation magnitude while
being unbiased across biological covariates.

In [1]:
import pathlib
from typing import Optional

import pandas as pd
import polars as pl

from image_ablation_analysis.regression.nested_regression import (
    bootstrap_nested_regression,
    BootstrapConfig,
    ColumnSpec,
)

## Pathing

In [2]:
results_dir = pathlib.Path(".") / "results"
if not results_dir.exists():
    raise FileNotFoundError(f"Results directory not found at {results_dir.resolve()}")

regression_input_data_file = results_dir / "for_regression_subsampled.parquet"
if not regression_input_data_file.exists():
    raise FileNotFoundError(f"Regression input data not found at {regression_input_data_file.resolve()}")

## Regression helper

In [3]:
def summarize_r2_scatter_bootstrap(
    boot_df: pd.DataFrame,
    output_csv: Optional[str | pathlib.Path] = None,
    group_cols: tuple[str, ...] = ("metric_name", "ablation_type"),
    restricted_col: str = "r2_restricted",
    partial_col: str = "partial_r2_x2",
    ci: float = 0.95,
) -> pd.DataFrame:
    
    required = set(group_cols) | {"boot_idx", restricted_col, partial_col}
    missing = sorted(required - set(boot_df.columns))
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    lower_q = (1 - ci) / 2
    upper_q = 1 - lower_q

    df = boot_df.copy()
    df[restricted_col] = pd.to_numeric(df[restricted_col], errors="coerce")
    df[partial_col] = pd.to_numeric(df[partial_col], errors="coerce")

    summary = (
        df.groupby(list(group_cols), dropna=False)
        .agg(
            n_boot=("boot_idx", "nunique"),

            restricted_r2_mean=(restricted_col, "mean"),
            restricted_r2_lower=(restricted_col, lambda x: x.quantile(lower_q)),
            restricted_r2_upper=(restricted_col, lambda x: x.quantile(upper_q)),

            partial_r2_mean=(partial_col, "mean"),
            partial_r2_lower=(partial_col, lambda x: x.quantile(lower_q)),
            partial_r2_upper=(partial_col, lambda x: x.quantile(upper_q)),
        )
        .reset_index()
        .sort_values(list(group_cols))
        .reset_index(drop=True)
    )

    if output_csv is not None:
        output_csv = pathlib.Path(output_csv)
        output_csv.parent.mkdir(parents=True, exist_ok=True)
        summary.to_csv(output_csv, index=False)

    return summary

In [4]:
regression_input = pl.read_parquet(regression_input_data_file).to_pandas()
print(len(regression_input))
regression_input.head()

1844400

,created_at,run_id,original_abs_path,original_rel_path,aug_abs_path,aug_rel_path,variant,config_id,params_json,param_fixed,...,Metadata_PositionX,Metadata_PositionY,Metadata_PositionZ,Metadata_Row,Metadata_Reimaged,ablation_package,ablation_type,hash,metric_name,metric_value
0,20260218T212130127579Z,0f57f65f-729e-4cc4-a651-121c34b36181,/mnt/data_nvme1/data/ALSF_pilot_data/SN0313537...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,/mnt/hdd20tb/alsf_ablation/SN0313537/BR0014397...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,xform_abl_gaussnoise=0.2_6339a071e1e884db,albumentations:GaussNoise:6339a071e1e884db,"{""backend"":""albumentations"",""transform_name"":""...",[],...,-0.000646,0.000646,-0.000006,3.0,False,albumentations,GaussNoise,6339a071e1e884db,lpips,0.712087
1,20260219T025541654122Z,41811ddb-a68d-4909-830b-cee3d15b03ee,/mnt/data_nvme1/data/ALSF_pilot_data/SN0313537...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,/mnt/hdd20tb/alsf_ablation/SN0313537/BR0014397...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,xform_abl_gamma=155.18_699b97b2f9705fc2,albumentations:RandomGamma:699b97b2f9705fc2,"{""backend"":""albumentations"",""transform_name"":""...",[],...,-0.000646,0.000646,-0.000006,3.0,False,albumentations,RandomGamma,699b97b2f9705fc2,foreground_ssim,0.457415
2,20260219T025541654122Z,41811ddb-a68d-4909-830b-cee3d15b03ee,/mnt/data_nvme1/data/ALSF_pilot_data/SN0313537...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,/mnt/hdd20tb/alsf_ablation/SN0313537/BR0014397...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,xform_abl_gamma=193.32_0c77f398c28c2341,albumentations:RandomGamma:0c77f398c28c2341,"{""backend"":""albumentations"",""transform_name"":""...",[],...,-0.000646,0.000646,-0.000006,3.0,False,albumentations,RandomGamma,0c77f398c28c2341,ssim,0.714855
3,20260219T025541654122Z,41811ddb-a68d-4909-830b-cee3d15b03ee,/mnt/data_nvme1/data/ALSF_pilot_data/SN0313537...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,/mnt/hdd20tb/alsf_ablation/SN0313537/BR0014397...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,xform_abl_gamma=155.18_699b97b2f9705fc2,albumentations:RandomGamma:699b97b2f9705fc2,"{""backend"":""albumentations"",""transform_name"":""...",[],...,-0.000646,0.000646,-0.000006,3.0,False,albumentations,RandomGamma,699b97b2f9705fc2,mae,0.006020
4,20260218T212130127579Z,0f57f65f-729e-4cc4-a651-121c34b36181,/mnt/data_nvme1/data/ALSF_pilot_data/SN0313537...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,/mnt/hdd20tb/alsf_ablation/SN0313537/BR0014397...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,xform_abl_gaussnoise=0.1_e473bcd5b5024cf6,albumentations:GaussNoise:e473bcd5b5024cf6,"{""backend"":""albumentations"",""transform_name"":""...",[],...,-0.000646,0.000646,-0.000006,3.0,False,albumentations,GaussNoise,e473bcd5b5024cf6,foreground_ssim,0.143215

## Shared boostrap/regression parameters
All regression analysis will share the same dependent variable, whichare the metric values as well as the first (restricted) independent variable which will be the parameter value. The full independent variable and the groupings of regression analysis will change based on the confounding variable being tested for.

In [5]:
regression_config = {
    "y": "metric_value",    # dependent variable, always metric value for this analysis
    "x1": "param_values",   # independent variable 1, always the ablation parameter values for this analysis
}

bootstrap_config = {
    "n_boot": 300,
    "sample_frac": 0.5,
    "replace": True,
    "standardize": False,
    "robust_cov": None,     # or "HC3"
    "min_group_size": 25,   # prevent regression on tiny groups
}

## Regression Analysis 1: Assessing confounding by seeding density

In [6]:
colspec = ColumnSpec(
    group_cols=("metric_name", "ablation_type"),
    x2="seeding_density", # full regression parameters
    x2_categorical=False,
    standardize_cols=("param_values", "seeding_density"),
    **regression_config
)

cfg = BootstrapConfig(
    **bootstrap_config
)

boot_res = bootstrap_nested_regression(regression_input, colspec, cfg)
boot_res.to_parquet(results_dir / "boot_nest_confluence.parquet", index=False)

Bootstrap groups:   0%|          | 0/42 [00:00<?, ?it/s]

In [7]:
summarize_r2_scatter_bootstrap(
    boot_res,
    output_csv=results_dir / "boot_nest_confluence_summary.csv",
)

,metric_name,ablation_type,n_boot,restricted_r2_mean,restricted_r2_lower,restricted_r2_upper,partial_r2_mean,partial_r2_lower,partial_r2_upper
0,dists,Dilate,300,0.498193,0.490481,0.506279,0.110758,1.032898e-01,0.117899
1,dists,Erode,300,0.321256,0.302854,0.340736,0.080498,7.062043e-02,0.090313
2,dists,GaussNoise,300,0.174465,0.164639,0.183303,0.078161,7.204976e-02,0.084883
3,dists,GaussianBlur,300,0.072706,0.066758,0.078518,0.089581,8.414954e-02,0.095466
4,dists,GridDistortion,300,0.571806,0.563669,0.581536,0.055190,4.879735e-02,0.060850
5,dists,RandomGamma,300,0.357259,0.347118,0.367703,0.000294,4.798050e-05,0.000646
6,foreground_psnr,Dilate,300,0.107254,0.101385,0.112247,0.000264,5.710948e-05,0.000625
7,foreground_psnr,Erode,300,0.135684,0.127479,0.143064,0.029366,2.501001e-02,0.033490
8,foreground_psnr,GaussNoise,300,0.712901,0.705940,0.719638,0.059674,5.169054e-02,0.068869
9,foreground_psnr,GaussianBlur,300,0.178592,0.168815,0.187460,0.005385,3.696183e-03,0.007236
10,foreground_psnr,GridDistortion,300,0.033495,0.028487,0.038907,0.035342,3.018456e-02,0.041079
11,foreground_psnr,RandomGamma,300,0.031771,0.029640,0.033790,0.000031,1.441212e-08,0.000149
12,foreground_ssim,Dilate,300,0.276207,0.267689,0.285791,0.000202,1.942221e-07,0.000733
13,foreground_ssim,Erode,300,0.101988,0.095078,0.109624,0.002625,1.405251e-03,0.004049
14,foreground_ssim,GaussNoise,300,0.302224,0.292334,0.311975,0.002265,1.100669e-03,0.003674
15,foreground_ssim,GaussianBlur,300,0.075840,0.068735,0.082921,0.000675,8.211406e-05,0.001706
16,foreground_ssim,GridDistortion,300,0.059152,0.053331,0.065583,0.019118,1.552032e-02,0.022961
17,foreground_ssim,RandomGamma,300,0.127701,0.119891,0.135829,0.000021,7.785497e-09,0.000117
18,lpips,Dilate,300,0.371795,0.360166,0.384207,0.244134,2.333989e-01,0.255674
19,lpips,Erode,300,0.143288,0.136406,0.150787,0.211042,2.019598e-01,0.220700
20,lpips,GaussNoise,300,0.375914,0.367457,0.384856,0.028680,2.493563e-02,0.033191
21,lpips,GaussianBlur,300,0.097142,0.089444,0.105444,0.249711,2.377088e-01,0.260192
22,lpips,GridDistortion,300,0.004981,0.003412,0.006857,0.266736,2.585241e-01,0.276476
23,lpips,RandomGamma,300,0.001419,0.000735,0.002344,0.000064,2.232713e-07,0.000235
24,mae,Dilate,300,0.054247,0.050402,0.058267,0.145177,1.375402e-01,0.153646
25,mae,Erode,300,0.242401,0.230538,0.255666,0.135881,1.246672e-01,0.149431
26,mae,GaussNoise,300,0.715471,0.711193,0.720171,0.047925,4.380877e-02,0.052220
27,mae,GaussianBlur,300,0.153412,0.146366,0.159856,0.122829,1.125825e-01,0.132365
28,mae,GridDistortion,300,0.023236,0.018904,0.028207,0.120710,1.078337e-01,0.133688
29,mae,RandomGamma,300,0.525018,0.519002,0.531030,0.012957,1.032270e-02,0.015890
30,psnr,Dilate,300,0.423020,0.410567,0.436830,0.083617,7.524348e-02,0.092202
31,psnr,Erode,300,0.333157,0.315527,0.349993,0.084461,7.463664e-02,0.096031
32,psnr,GaussNoise,300,0.814471,0.811853,0.817402,0.020107,1.691532e-02,0.023519
33,psnr,GaussianBlur,300,0.004116,0.002031,0.006877,0.128291,1.186375e-01,0.139583
34,psnr,GridDistortion,300,0.025576,0.019973,0.030608,0.034194,2.776083e-02,0.041737
35,psnr,RandomGamma,300,0.120204,0.111211,0.131293,0.044268,3.829919e-02,0.050640
36,ssim,Dilate,300,0.224066,0.214808,0.233402,0.216839,2.066093e-01,0.226496
37,ssim,Erode,300,0.097639,0.088953,0.106726,0.180237,1.669733e-01,0.193776
38,ssim,GaussNoise,300,0.606765,0.599800,0.613941,0.095165,8.846591e-02,0.101039
39,ssim,GaussianBlur,300,0.043576,0.038670,0.048561,0.170598,1.601559e-01,0.181544
40,ssim,GridDistortion,300,0.028858,0.024031,0.034932,0.189825,1.778846e-01,0.201937
41,ssim,RandomGamma,300,0.012766,0.010012,0.015537,0.000116,1.814330e-06,0.000367

## Regression Analysis 2: Assessing confounding by cell lines

In [8]:
colspec = ColumnSpec(
    group_cols=("metric_name", "ablation_type"),
    x2="cell_line", # categorical var
    x2_categorical=True,
    standardize_cols=("param_values",),
    **regression_config
)

cfg = BootstrapConfig(
    **bootstrap_config
)

boot_res = bootstrap_nested_regression(regression_input, colspec, cfg)
boot_res.to_parquet(results_dir / "boot_nest_cell_line.parquet", index=False)

Bootstrap groups:   0%|          | 0/42 [00:00<?, ?it/s]

In [9]:
summarize_r2_scatter_bootstrap(
    boot_res,
    output_csv=results_dir / "boot_nest_cell_line_summary.csv",
)

,metric_name,ablation_type,n_boot,restricted_r2_mean,restricted_r2_lower,restricted_r2_upper,partial_r2_mean,partial_r2_lower,partial_r2_upper
0,dists,Dilate,300,0.498193,0.490481,0.506279,0.110159,0.102869,0.118532
1,dists,Erode,300,0.321256,0.302854,0.340736,0.126893,0.111868,0.141605
2,dists,GaussNoise,300,0.174465,0.164639,0.183303,0.028320,0.024309,0.032695
3,dists,GaussianBlur,300,0.072706,0.066758,0.078518,0.046145,0.040798,0.051156
4,dists,GridDistortion,300,0.571806,0.563669,0.581536,0.052346,0.047063,0.058327
5,dists,RandomGamma,300,0.357259,0.347118,0.367703,0.017781,0.015388,0.020288
6,foreground_psnr,Dilate,300,0.107254,0.101385,0.112247,0.304774,0.297129,0.312580
7,foreground_psnr,Erode,300,0.135684,0.127479,0.143064,0.133617,0.125048,0.141118
8,foreground_psnr,GaussNoise,300,0.712901,0.705940,0.719638,0.072444,0.062171,0.083076
9,foreground_psnr,GaussianBlur,300,0.178592,0.168815,0.187460,0.333650,0.321679,0.345457
10,foreground_psnr,GridDistortion,300,0.033495,0.028487,0.038907,0.566505,0.546124,0.583537
11,foreground_psnr,RandomGamma,300,0.031771,0.029640,0.033790,0.001489,0.000844,0.002262
12,foreground_ssim,Dilate,300,0.276207,0.267689,0.285791,0.571997,0.561633,0.583748
13,foreground_ssim,Erode,300,0.101988,0.095078,0.109624,0.394301,0.381422,0.406920
14,foreground_ssim,GaussNoise,300,0.302224,0.292334,0.311975,0.122670,0.113157,0.132959
15,foreground_ssim,GaussianBlur,300,0.075840,0.068735,0.082921,0.178841,0.165360,0.189009
16,foreground_ssim,GridDistortion,300,0.059152,0.053331,0.065583,0.183671,0.172435,0.193276
17,foreground_ssim,RandomGamma,300,0.127701,0.119891,0.135829,0.017345,0.015502,0.019681
18,lpips,Dilate,300,0.371795,0.360166,0.384207,0.118342,0.110337,0.126673
19,lpips,Erode,300,0.143288,0.136406,0.150787,0.152830,0.143801,0.161620
20,lpips,GaussNoise,300,0.375914,0.367457,0.384856,0.062633,0.056140,0.068532
21,lpips,GaussianBlur,300,0.097142,0.089444,0.105444,0.207248,0.197358,0.218239
22,lpips,GridDistortion,300,0.004981,0.003412,0.006857,0.117944,0.111612,0.126186
23,lpips,RandomGamma,300,0.001419,0.000735,0.002344,0.003828,0.002817,0.005016
24,mae,Dilate,300,0.054247,0.050402,0.058267,0.157435,0.148473,0.165101
25,mae,Erode,300,0.242401,0.230538,0.255666,0.074112,0.064232,0.085566
26,mae,GaussNoise,300,0.715471,0.711193,0.720171,0.079188,0.072250,0.085893
27,mae,GaussianBlur,300,0.153412,0.146366,0.159856,0.116446,0.105991,0.127090
28,mae,GridDistortion,300,0.023236,0.018904,0.028207,0.127764,0.116595,0.139720
29,mae,RandomGamma,300,0.525018,0.519002,0.531030,0.008784,0.006448,0.011084
30,psnr,Dilate,300,0.423020,0.410567,0.436830,0.130295,0.121660,0.138564
31,psnr,Erode,300,0.333157,0.315527,0.349993,0.110298,0.099344,0.121694
32,psnr,GaussNoise,300,0.814471,0.811853,0.817402,0.017480,0.014583,0.020743
33,psnr,GaussianBlur,300,0.004116,0.002031,0.006877,0.227374,0.213333,0.241883
34,psnr,GridDistortion,300,0.025576,0.019973,0.030608,0.184560,0.170580,0.200594
35,psnr,RandomGamma,300,0.120204,0.111211,0.131293,0.027557,0.022194,0.032515
36,ssim,Dilate,300,0.224066,0.214808,0.233402,0.116554,0.107696,0.125298
37,ssim,Erode,300,0.097639,0.088953,0.106726,0.113486,0.103136,0.125413
38,ssim,GaussNoise,300,0.606765,0.599800,0.613941,0.077852,0.071320,0.084222
39,ssim,GaussianBlur,300,0.043576,0.038670,0.048561,0.114708,0.104735,0.124814
40,ssim,GridDistortion,300,0.028858,0.024031,0.034932,0.096878,0.088704,0.107181
41,ssim,RandomGamma,300,0.012766,0.010012,0.015537,0.002930,0.001968,0.003962