# 2.4. Perform nested regression with bootstrapping of metric value against magnitude of ablation and biological covariate confluence

Assesses how each metrics is able to capture the variation in ablation magnitude while
being unbiased across biological covariates.

In [1]:
import pathlib
from typing import Optional

import pandas as pd
import polars as pl

from image_ablation_analysis.regression.nested_regression import (
    bootstrap_nested_regression,
    BootstrapConfig,
    ColumnSpec,
)

## Pathing

In [2]:
results_dir = pathlib.Path(".") / "results"
if not results_dir.exists():
    raise FileNotFoundError(f"Results directory not found at {results_dir.resolve()}")

regression_input_data_file = results_dir / "for_analysis_subsampled.parquet"
if not regression_input_data_file.exists():
    raise FileNotFoundError(f"Regression input data not found at {regression_input_data_file.resolve()}")

## Regression helper

In [3]:
def summarize_r2_scatter_bootstrap(
    boot_df: pd.DataFrame,
    output_csv: Optional[str | pathlib.Path] = None,
    group_cols: tuple[str, ...] = ("metric_name", "ablation_type"),
    restricted_col: str = "r2_restricted",
    partial_col: str = "partial_r2_x2",
    ci: float = 0.95,
) -> pd.DataFrame:
    
    required = set(group_cols) | {"boot_idx", restricted_col, partial_col}
    missing = sorted(required - set(boot_df.columns))
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    lower_q = (1 - ci) / 2
    upper_q = 1 - lower_q

    df = boot_df.copy()
    df[restricted_col] = pd.to_numeric(df[restricted_col], errors="coerce")
    df[partial_col] = pd.to_numeric(df[partial_col], errors="coerce")

    summary = (
        df.groupby(list(group_cols), dropna=False)
        .agg(
            n_boot=("boot_idx", "nunique"),

            restricted_r2_mean=(restricted_col, "mean"),
            restricted_r2_lower=(restricted_col, lambda x: x.quantile(lower_q)),
            restricted_r2_upper=(restricted_col, lambda x: x.quantile(upper_q)),

            partial_r2_mean=(partial_col, "mean"),
            partial_r2_lower=(partial_col, lambda x: x.quantile(lower_q)),
            partial_r2_upper=(partial_col, lambda x: x.quantile(upper_q)),
        )
        .reset_index()
        .sort_values(list(group_cols))
        .reset_index(drop=True)
    )

    if output_csv is not None:
        output_csv = pathlib.Path(output_csv)
        output_csv.parent.mkdir(parents=True, exist_ok=True)
        summary.to_csv(output_csv, index=False)

    return summary

In [4]:
regression_input = pl.read_parquet(regression_input_data_file).to_pandas()
print(len(regression_input))
regression_input.head()

1844400

,created_at,run_id,original_abs_path,original_rel_path,aug_abs_path,aug_rel_path,variant,config_id,params_json,param_fixed,...,Metadata_PositionX,Metadata_PositionY,Metadata_PositionZ,Metadata_Row,Metadata_Reimaged,ablation_package,ablation_type,hash,metric_name,metric_value
0,20260218T212130127579Z,0f57f65f-729e-4cc4-a651-121c34b36181,/mnt/data_nvme1/data/ALSF_pilot_data/SN0313537...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,/mnt/hdd20tb/alsf_ablation/SN0313537/BR0014397...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,xform_abl_gaussnoise=0.2_6339a071e1e884db,albumentations:GaussNoise:6339a071e1e884db,"{""backend"":""albumentations"",""transform_name"":""...",[],...,-0.000646,0.000646,-0.000006,3.0,False,albumentations,GaussNoise,6339a071e1e884db,lpips,0.712087
1,20260219T025541654122Z,41811ddb-a68d-4909-830b-cee3d15b03ee,/mnt/data_nvme1/data/ALSF_pilot_data/SN0313537...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,/mnt/hdd20tb/alsf_ablation/SN0313537/BR0014397...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,xform_abl_gamma=155.18_699b97b2f9705fc2,albumentations:RandomGamma:699b97b2f9705fc2,"{""backend"":""albumentations"",""transform_name"":""...",[],...,-0.000646,0.000646,-0.000006,3.0,False,albumentations,RandomGamma,699b97b2f9705fc2,foreground_ssim,0.457415
2,20260219T025541654122Z,41811ddb-a68d-4909-830b-cee3d15b03ee,/mnt/data_nvme1/data/ALSF_pilot_data/SN0313537...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,/mnt/hdd20tb/alsf_ablation/SN0313537/BR0014397...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,xform_abl_gamma=193.32_0c77f398c28c2341,albumentations:RandomGamma:0c77f398c28c2341,"{""backend"":""albumentations"",""transform_name"":""...",[],...,-0.000646,0.000646,-0.000006,3.0,False,albumentations,RandomGamma,0c77f398c28c2341,ssim,0.714855
3,20260219T025541654122Z,41811ddb-a68d-4909-830b-cee3d15b03ee,/mnt/data_nvme1/data/ALSF_pilot_data/SN0313537...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,/mnt/hdd20tb/alsf_ablation/SN0313537/BR0014397...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,xform_abl_gamma=155.18_699b97b2f9705fc2,albumentations:RandomGamma:699b97b2f9705fc2,"{""backend"":""albumentations"",""transform_name"":""...",[],...,-0.000646,0.000646,-0.000006,3.0,False,albumentations,RandomGamma,699b97b2f9705fc2,mae,0.006020
4,20260218T212130127579Z,0f57f65f-729e-4cc4-a651-121c34b36181,/mnt/data_nvme1/data/ALSF_pilot_data/SN0313537...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,/mnt/hdd20tb/alsf_ablation/SN0313537/BR0014397...,SN0313537/BR00143976__2024-07-04T16_04_45-Meas...,xform_abl_gaussnoise=0.1_e473bcd5b5024cf6,albumentations:GaussNoise:e473bcd5b5024cf6,"{""backend"":""albumentations"",""transform_name"":""...",[],...,-0.000646,0.000646,-0.000006,3.0,False,albumentations,GaussNoise,e473bcd5b5024cf6,foreground_ssim,0.143215

## Shared boostrap/regression parameters
All regression analysis will share the same dependent variable, whichare the metric values as well as the first (restricted) independent variable which will be the parameter value. The full independent variable and the groupings of regression analysis will change based on the confounding variable being tested for.

In [5]:
regression_config = {
    "y": "metric_value",    # dependent variable, always metric value for this analysis
    "x1": "param_values",   # independent variable 1, always the ablation parameter values for this analysis
}

bootstrap_config = {
    "n_boot": 300,
    "sample_frac": 0.5,
    "replace": True,
    "standardize": False,
    "robust_cov": None,     # or "HC3"
    "min_group_size": 25,   # prevent regression on tiny groups
}

## Regression Analysis 1: Assessing confounding by seeding density

In [6]:
colspec = ColumnSpec(
    group_cols=("metric_name", "ablation_type"),
    x2="seeding_density", # full regression parameters
    x2_categorical=False,
    standardize_cols=("param_values", "seeding_density"),
    **regression_config
)

cfg = BootstrapConfig(
    **bootstrap_config
)

boot_res = bootstrap_nested_regression(regression_input, colspec, cfg)
boot_res.to_parquet(results_dir / "boot_nest_confluence.parquet", index=False)

Bootstrap groups:   0%|          | 0/42 [00:00<?, ?it/s]

In [7]:
summarize_r2_scatter_bootstrap(
    boot_res,
    output_csv=results_dir / "boot_nest_confluence_summary.csv",
)

,metric_name,ablation_type,n_boot,restricted_r2_mean,restricted_r2_lower,restricted_r2_upper,partial_r2_mean,partial_r2_lower,partial_r2_upper
0,dists,Dilate,300,0.333146,0.322511,0.344332,0.077436,6.993122e-02,0.084361
1,dists,Erode,300,0.448721,0.438195,0.459475,0.092615,8.521768e-02,0.100562
2,dists,GaussNoise,300,0.112250,0.104277,0.121178,0.059226,5.244090e-02,0.066842
3,dists,GaussianBlur,300,0.170199,0.161275,0.179939,0.076169,6.861769e-02,0.082725
4,dists,GridDistortion,300,0.672356,0.664987,0.679806,0.029703,2.538851e-02,0.034636
5,dists,RandomGamma,300,0.202411,0.194180,0.210199,0.000046,5.179250e-08,0.000210
6,foreground_psnr,Dilate,300,0.206450,0.197217,0.218368,0.000571,9.137378e-05,0.001383
7,foreground_psnr,Erode,300,0.107291,0.099907,0.116198,0.000137,7.851101e-07,0.000571
8,foreground_psnr,GaussNoise,300,0.889034,0.886595,0.891238,0.052885,4.649919e-02,0.059514
9,foreground_psnr,GaussianBlur,300,0.043879,0.038544,0.049774,0.000061,1.315380e-07,0.000323
10,foreground_psnr,GridDistortion,300,0.007409,0.005253,0.010163,0.002153,1.055718e-03,0.003673
11,foreground_psnr,RandomGamma,300,0.024918,0.022967,0.026966,0.000025,3.095450e-08,0.000113
12,foreground_ssim,Dilate,300,0.202401,0.190138,0.215198,0.000802,1.720449e-04,0.001651
13,foreground_ssim,Erode,300,0.173879,0.164863,0.183103,0.000471,5.150519e-05,0.001181
14,foreground_ssim,GaussNoise,300,0.209182,0.198556,0.220529,0.002464,1.292894e-03,0.003817
15,foreground_ssim,GaussianBlur,300,0.056576,0.051204,0.062171,0.000105,2.495944e-07,0.000412
16,foreground_ssim,GridDistortion,300,0.034769,0.029937,0.039873,0.014934,1.150525e-02,0.018575
17,foreground_ssim,RandomGamma,300,0.143214,0.136134,0.151728,0.000032,4.313988e-08,0.000164
18,lpips,Dilate,300,0.205274,0.196790,0.216536,0.181613,1.714369e-01,0.190840
19,lpips,Erode,300,0.208577,0.199730,0.217748,0.183367,1.740122e-01,0.192728
20,lpips,GaussNoise,300,0.200259,0.188913,0.212621,0.048323,4.274592e-02,0.054749
21,lpips,GaussianBlur,300,0.068345,0.062419,0.075228,0.200144,1.903643e-01,0.210416
22,lpips,GridDistortion,300,0.174148,0.163902,0.183455,0.246752,2.373627e-01,0.257338
23,lpips,RandomGamma,300,0.029975,0.025963,0.034130,0.000404,1.118115e-04,0.000826
24,mae,Dilate,300,0.139897,0.132550,0.147581,0.112718,1.032654e-01,0.122257
25,mae,Erode,300,0.109455,0.102248,0.116640,0.145693,1.359849e-01,0.155426
26,mae,GaussNoise,300,0.536696,0.529194,0.543814,0.049352,4.344974e-02,0.055825
27,mae,GaussianBlur,300,0.045915,0.041252,0.051605,0.132680,1.237216e-01,0.142788
28,mae,GridDistortion,300,0.029708,0.025036,0.034737,0.106350,9.714640e-02,0.115575
29,mae,RandomGamma,300,0.091449,0.085479,0.096434,0.011006,9.072493e-03,0.012980
30,psnr,Dilate,300,0.224391,0.212657,0.234695,0.064711,5.779008e-02,0.070870
31,psnr,Erode,300,0.181876,0.171772,0.190487,0.069004,6.222995e-02,0.076026
32,psnr,GaussNoise,300,0.871450,0.868568,0.874246,0.032718,2.792844e-02,0.037574
33,psnr,GaussianBlur,300,0.071624,0.064041,0.080444,0.070193,6.294774e-02,0.076641
34,psnr,GridDistortion,300,0.023910,0.020049,0.028345,0.031347,2.647385e-02,0.036174
35,psnr,RandomGamma,300,0.130555,0.122707,0.137714,0.039381,3.563096e-02,0.043429
36,ssim,Dilate,300,0.204897,0.195286,0.213973,0.158294,1.472470e-01,0.169587
37,ssim,Erode,300,0.172472,0.164052,0.181097,0.170894,1.612455e-01,0.181908
38,ssim,GaussNoise,300,0.582837,0.573621,0.592322,0.098940,9.067329e-02,0.107769
39,ssim,GaussianBlur,300,0.050449,0.045620,0.056105,0.159098,1.477012e-01,0.168835
40,ssim,GridDistortion,300,0.040376,0.034699,0.046505,0.193259,1.831007e-01,0.205263
41,ssim,RandomGamma,300,0.036572,0.032321,0.040691,0.000036,8.437052e-08,0.000173

## Regression Analysis 2: Assessing confounding by cell lines

In [8]:
colspec = ColumnSpec(
    group_cols=("metric_name", "ablation_type"),
    x2="cell_line", # categorical var
    x2_categorical=True,
    standardize_cols=("param_values",),
    **regression_config
)

cfg = BootstrapConfig(
    **bootstrap_config
)

boot_res = bootstrap_nested_regression(regression_input, colspec, cfg)
boot_res.to_parquet(results_dir / "boot_nest_cell_line.parquet", index=False)

Bootstrap groups:   0%|          | 0/42 [00:00<?, ?it/s]

In [9]:
summarize_r2_scatter_bootstrap(
    boot_res,
    output_csv=results_dir / "boot_nest_cell_line_summary.csv",
)

,metric_name,ablation_type,n_boot,restricted_r2_mean,restricted_r2_lower,restricted_r2_upper,partial_r2_mean,partial_r2_lower,partial_r2_upper
0,dists,Dilate,300,0.333146,0.322511,0.344332,0.056038,0.049346,0.062477
1,dists,Erode,300,0.448721,0.438195,0.459475,0.068488,0.062534,0.074851
2,dists,GaussNoise,300,0.112250,0.104277,0.121178,0.034945,0.030441,0.041503
3,dists,GaussianBlur,300,0.170199,0.161275,0.179939,0.033587,0.028624,0.039012
4,dists,GridDistortion,300,0.672356,0.664987,0.679806,0.030518,0.025575,0.035574
5,dists,RandomGamma,300,0.202411,0.194180,0.210199,0.018191,0.015789,0.020638
6,foreground_psnr,Dilate,300,0.206450,0.197217,0.218368,0.265293,0.254779,0.274316
7,foreground_psnr,Erode,300,0.107291,0.099907,0.116198,0.171184,0.160786,0.180781
8,foreground_psnr,GaussNoise,300,0.889034,0.886595,0.891238,0.048141,0.042142,0.054292
9,foreground_psnr,GaussianBlur,300,0.043879,0.038544,0.049774,0.210995,0.198517,0.222304
10,foreground_psnr,GridDistortion,300,0.007409,0.005253,0.010163,0.141498,0.131848,0.151677
11,foreground_psnr,RandomGamma,300,0.024918,0.022967,0.026966,0.000747,0.000377,0.001228
12,foreground_ssim,Dilate,300,0.202401,0.190138,0.215198,0.264408,0.253431,0.276166
13,foreground_ssim,Erode,300,0.173879,0.164863,0.183103,0.223168,0.212220,0.234706
14,foreground_ssim,GaussNoise,300,0.209182,0.198556,0.220529,0.085859,0.077941,0.095807
15,foreground_ssim,GaussianBlur,300,0.056576,0.051204,0.062171,0.249313,0.235828,0.261736
16,foreground_ssim,GridDistortion,300,0.034769,0.029937,0.039873,0.145047,0.134671,0.154640
17,foreground_ssim,RandomGamma,300,0.143214,0.136134,0.151728,0.028416,0.025723,0.031064
18,lpips,Dilate,300,0.205274,0.196790,0.216536,0.093359,0.085325,0.101117
19,lpips,Erode,300,0.208577,0.199730,0.217748,0.100826,0.093220,0.109904
20,lpips,GaussNoise,300,0.200259,0.188913,0.212621,0.074630,0.067126,0.082692
21,lpips,GaussianBlur,300,0.068345,0.062419,0.075228,0.115381,0.107200,0.123454
22,lpips,GridDistortion,300,0.174148,0.163902,0.183455,0.122845,0.114311,0.131076
23,lpips,RandomGamma,300,0.029975,0.025963,0.034130,0.006388,0.005112,0.008033
24,mae,Dilate,300,0.139897,0.132550,0.147581,0.082560,0.075189,0.091368
25,mae,Erode,300,0.109455,0.102248,0.116640,0.099376,0.090743,0.109495
26,mae,GaussNoise,300,0.536696,0.529194,0.543814,0.043791,0.038103,0.050682
27,mae,GaussianBlur,300,0.045915,0.041252,0.051605,0.096274,0.088227,0.105453
28,mae,GridDistortion,300,0.029708,0.025036,0.034737,0.088333,0.080321,0.097488
29,mae,RandomGamma,300,0.091449,0.085479,0.096434,0.009877,0.007927,0.011983
30,psnr,Dilate,300,0.224391,0.212657,0.234695,0.168078,0.157993,0.180280
31,psnr,Erode,300,0.181876,0.171772,0.190487,0.157359,0.147765,0.166704
32,psnr,GaussNoise,300,0.871450,0.868568,0.874246,0.028669,0.023816,0.033965
33,psnr,GaussianBlur,300,0.071624,0.064041,0.080444,0.171600,0.163093,0.182346
34,psnr,GridDistortion,300,0.023910,0.020049,0.028345,0.113411,0.105346,0.121370
35,psnr,RandomGamma,300,0.130555,0.122707,0.137714,0.022479,0.019453,0.025813
36,ssim,Dilate,300,0.204897,0.195286,0.213973,0.091836,0.083572,0.099965
37,ssim,Erode,300,0.172472,0.164052,0.181097,0.098982,0.090723,0.108032
38,ssim,GaussNoise,300,0.582837,0.573621,0.592322,0.061007,0.054298,0.068093
39,ssim,GaussianBlur,300,0.050449,0.045620,0.056105,0.100985,0.092764,0.109573
40,ssim,GridDistortion,300,0.040376,0.034699,0.046505,0.087618,0.079864,0.096088
41,ssim,RandomGamma,300,0.036572,0.032321,0.040691,0.001469,0.000876,0.002230